### PR TITLE
Add control_level slider.

### PR DESCRIPTION
**Pull request by mmarsalko**
I decided to dig into the bug with Cadmus 0.2 not working on a lot of people's systems (including mine). Looks like the "control" value was missing, so I went ahead and added that back in, and made a slider so the user can set their own control level manually.
I've never messed with PyQt or pulse at this level, so it was a bit of fun learning how it all worked.

image

Hope you don't mind the cold PR out of nowhere. :)

### CODE REVIEW

**Comment by PixsaOJ** [comment]
Can we accept this request?

**Comment by mastastealth** [comment]
@mmarsalko Would you happen to be able to provide a binary for the non-Python inclined while we wait for a merge? :sweat_smile:

**Comment by mmarsalko** [comment]
> @mmarsalko Would you happen to be able to provide a binary for the non-Python inclined while we wait for a merge? sweat_smile

Sorry, I wish I could, but I have no idea how to build it! The included build scripts use docker containers I don't have access to. 😬

**Comment by JCGoran** [comment]
Seeing as how the current build process for a `.deb` file is somewhat involved, and I'm affected by the no-audio issue as well, I've put together a small [shell script](https://gist.github.com/JCGoran/e39c14ee6fdb03b4b405834ddf3d0be4) which can be used to build and run Cadmus, I'm just posting it here in case someone finds it useful.
I've verified that Cadmus builds successfully and runs as intended when using it, on several different machines, and the packages required as well as the usage instructions are written down at the top of the script.

**Comment by christf** [comment]
> Seeing as how the current build process for a `.deb` file is somewhat involved, and I'm affected by the no-audio issue as well, I've put together a small [shell script](https://gist.github.com/JCGoran/e39c14ee6fdb03b4b405834ddf3d0be4) which can be used to build and run Cadmus, I'm just posting it here in case someone finds it useful.
> I've verified that Cadmus builds successfully and runs as intended when using it, on several different machines, and the packages required as well as the usage instructions are written down at the top of the script.

thank you for this. The first line should start a bash instead of an sh. After changing that, it started to work for me.

Unfortunately pyqt installationm then fails
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-q6wrtrnb/PyQt5/setup.py'

**Comment by JCGoran** [comment]
> Traceback (most recent call last):
> File "", line 1, in
> File "/usr/lib/python3.7/tokenize.py", line 447, in open
> buffer = _builtin_open(filename, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-q6wrtrnb/PyQt5/setup.py'

Seems to be a problem with `pip` being too old, see [this stackoverflow answer](https://stackoverflow.com/a/59797479). I've updated the script with the various feedback I've received, hopefully the new version eliminates most of the common problems mentioned, including the one above.

**Comment by livkx** [comment]
As it looks like the author of cadmus has abandoned the project, I've forked it and merged in your fix @mmarsalko and I'm intending on keeping it up to date and working on this project in my spare time.

If anyone would like to contribute, I'd like to invite you to do it on my repo so it will be looked after.

To anyone else, you can find a release .deb to install with the fix at https://github.com/livkx/cadmus/releases

**Comment by josh-richardson** [comment]
Sorry, things have been crazy at work lately & I haven't had time for this. I'll merge this now & see what I can do about getting a release out tomorrow.

**Comment by livkx** [comment]
@josh-richardson Right after I started trying to look after this project in my fork repo, assuming you’d gone MIA, you’ve returned 😁If you’re expecting to be too busy to look after this project, I’m happy to offer assistance in maintaining the repo and releases as I started doing on my fork. Feel free to email me noop@despacito.co.uk

**Comment by kieran85james** [comment]
> @josh-richardson Right after I started trying to look after this project in my fork repo, assuming you’d gone MIA, you’ve returned If you’re expecting to be too busy to look after this project, I’m happy to offer assistance in maintaining the repo and releases as I started doing on my fork. Feel free to email me [noop@despacito.co.uk](mailto:noop@despacito.co.uk)

It would be good to have more than one person with the ability to merge pull requests & getting the releases out.

**Comment by AtomToast** [comment]
So about the release? .\_.

**Comment by livkx** [comment]
@AtomToast https://github.com/livkx/cadmus/releases/tag/0.0.3

**Comment by AtomToast** [comment]
So where are the official development and releases now?

**Comment by josh-richardson** [comment]
Released here: https://github.com/josh-richardson/cadmus/releases/tag/0.0.3

Will endeavor to be more active but have been working rather long hours lately.

**Comment by LiamDawe** [comment]
Hi, the slider doesn't appear in the latest AppImage provided on that tag.

https://imgur.com/a/ECOLiJE

It's just...a blank box at the bottom.

**Comment by tlefevre** [comment]
Same on Ubuntu 20.04 for me.

**Comment by sabatmonk** [comment]
No slider for me on Ubuntu 20.10

**Pull request merged**
