### PR TITLE
Changed slider to checkboxes and fixed pulse latency

### PR DESCRIPTION
**Pull request by pstoebenau**
- I changed the slider to checkboxes because the slider didn't work in some Linux distros.
- Pulse audio would have terrible latency when set to 1 millisec. I set it to 200 as a default value that should work for most microphones.

### CODE REVIEW

**Comment by josh-richardson** [comment]
Thanks for this, I'll test it tonight. I might make the checkboxes an option via a parameter or an options menu, rather than the default, as well as making the latency user-configurable.

**Comment by pstoebenau** [comment]
Yeah it would be awesome if it was user configurable. I do think for now it's best to have defaults though. Because I'm sure this is a problem for a lot of users.

Thanks for your response.

**Comment by pstoebenau** [comment]
Hey, it's been a while and I think it would be best to just add these changes. The latency I have with the current release is unusable. Thanks again.

**Comment by IniasP** [comment]
I can confirm the checkboxes work for me whereas the slider doesn't show up (Kubuntu 20.10, Qt 5.14.2).

**Comment by kristofvloock** [comment]
The checkboxes work for me as well, while the slider doesn't show up (Kubuntu 20.04, Qt 5.12.8).

**Pull request closed without merging**
